development:
  adapter: postgresql
  encoding: unicode
  pool: 10
  database: splitsmart_dev
  host: localhost
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  pool: 10
  database: splitsmart_test
  host: localhost
  username:
  password:

production:
  url: <%= ENV['DATABASE_URL'] %>